### ISSUE TITLE
flow rate integral evaluated at wrong height?

### ISSUE THREAD

**Issue by gogannes** [TUDelft-DataDrivenControl/FLORISSE_M#11]
https://github.com/TUDelft-DataDrivenControl/FLORISSE_M/blob/bff791955d80ff2901e98271d64f60c9375b121e/submodelDefinitions/flowRateIntegrals.m#L47

Hey Guys,
While simulating turbines with different hub height, Bastian and I figured out a potential mistake in the implementation of the numerical integration.
We believe that the referenced code line should be replaced with
`zabs = @(z) z+(dw_turbine.hub_height);`
In the current version, the interal is evaluated at the upwind turbine wake height instead of downwind turbine hub height.

We're not 100% sure yet, but believe you understand your code better than we do ;)

Best,
Johannes and Bastian

**Comment by RmStorm** [comment]
Hey Johannes and Bastian, you are correct.
z is centered on the downwind turbine rotor on the wake.
```
VelocityFun =@(y,z) (~mask(y,z).*U_inf(zabs(z))+...
mask(y,z).*uw_wake.V(U_inf(zabs(z)),deltax,dY_wc(y),dZ_wc(z)))./U_inf(zabs(z));
```
Should have been
```
VelocityFun =@(y,z) (~mask(y,z).*U_inf(zabs(dZ_wc(z)))+...
mask(y,z).*uw_wake.V(U_inf(zabs(dZ_wc(z))),deltax,dY_wc(y),dZ_wc(z)))./U_inf(zabs(dZ_wc(z)));
```
In that way z would first have become wake centered and than moved back to its absolute coordinate.
I implemented your solution which is clearer and added comments to the file as well!

I was not exactly sure how to add that commit to this pull request so i created and merged a new PR #12
