### ISSUE TITLE
Updating the calibration data

### ISSUE THREAD

**Issue by moldera91** [TUDelft-DataDrivenControl/FLORISSE_M#13]
https://github.com/TUDelft-DataDrivenControl/FLORISSE_M/blob/c8ed65cb4468c5d362ab6a02879b34baa724230a/coreFunctions/calibrationFunctions/calibrationCostFunc.m#L34

Hello everyone,

Since the parameters to be calibrated are defined by modelData, should the code be changed to    
" calibrationData(ii).inputData.wakeModel.modelData.(paramSet{jj}) = x(jj); " ?

Best regards,
Anil Molder

**Comment by Bartdoekemeijer** [comment]
Hi Anil,

The initial idea of this branch was to have the calibration function be able to estimate _any_ particular set of parameters that go into FLORIS. For offline model parameter tuning, you will indeed want to fit the modelData parameters to a large set of high-fidelity data (e.g., time-averaged power signals, flow fields). However, this function should also be able to deal with the online estimation of, for example, the wind direction or wind speed in the field. 

This calibration branch is an initial setup I wrote several months ago to give an idea of the framework necessary. It is by no means a finalized or usable product, as you may have figured out too. The current function mainly focuses on the latter objective: online estimation of the ambient conditions.

We are currently working on refactoring FLORIS for computational efficiency, usability, and making it developer-friendly. We will extract the calibration & optimization functions from the FLORIS core, and add them as separate example use cases, to make the FLORIS core light and flexible. You will be able to easily define your own cost function, making it easy to tune whichever parameters you need estimated. Hence, the calibration branch is discontinued for the time being.
