### ISSUE TITLE
Comment/Question

### ISSUE THREAD

**Issue by gogannes** [TUDelft-DataDrivenControl/FLORISSE_M#2]
Hey Guys, 
I think you made great work here. 
I'm currently comparing your implementation with the one we made at TUM. 

I have a small issue here: 
In floris_loadSettings.m it says that inputData.aU is given in degrees (and the value does only make sense in degrees):
> inputData.aU            = 12.0; % units: degrees

However, when the value is used in floris_initwake.m you assume a value in radians:
> wake.mU = inputData.MU/cos(inputData.aU+inputData.bU*turbine.YawWF);

Do I miss something here?

Best,
Johannes

**Comment by RmStorm** [comment]
Hey Johannes,

You are not missing anything. It is indeed an error, I have changed the value to radians but I'm still not exactly sure where this expression comes from. It seems to increase velocity recovery with increasing yaw angle which seems backward to me.

Best,
Roald
