### ISSUE TITLE
minor issue on visualizer.m

### ISSUE THREAD

**Issue by gogannes** [TUDelft-DataDrivenControl/FLORISSE_M#25]
when running an example e.g. `simulationLogarithmicInflow.m`, an error pops up when executing 
`visTool = visualizer(florisRunner);
visTool.plot3dWF();
visTool.plot2dIF();`

> Error using  .' 
> Transpose on ND array is not defined. Use PERMUTE instead.
> Error in interp2 (line 132)
>         V = V.';
> Error in visualizer/plot2dIF (line 120)
>                 obj.flowFieldIF.U = reshape(interp2(obj.flowfieldMain.X, ... 

As far as I understand the flow field is computed in `visualizer.m` only if necessary. As there are those internal checks, I would have expected the code to run without problems... However it doesn't seem to work (at least in my case).

This is clearly nothing important, I wanted to note it here only for the person who touches `visualizer.m` next time.

**Comment by Bartdoekemeijer** [comment]
Hey Johannes,

Thanks for creating this bug report. I have pushed a fix in the _dev_ branch that is supposed to resolve this issue. Let me know if it persists.

Thanks!
Bart

**Comment by gogannes** [comment]
Hey Bart,

I tested the dev branch and the bug seems to be fixed. 
Great to see that you keep the project running!

Best,
Johannes
