### ISSUE TITLE
Problem with deficit integral for centrally impinging wakes

### ISSUE THREAD

**Issue by gogannes** [TUDelft-DataDrivenControl/FLORISSE_M#28]
There seems to be a problem/error/bug with the self similar gaussian wake if it hits a downstream turbine centraly.
It is easy to reproduce the error using the example file `simulationLogarithmicInflow.m`. Just add `subModels.modelData.ad=0;` and `subModels.modelData.bd=0;` after the subModel definition. 

I assume the problem is caused when the deficit integral is computed using the bivariate cumulative distribution function. 

Until resolved, it is possible to fix the problem by replacing `deltax < obj.x0` with `1` in line 117 of `self_similar_gaussian_velocity.m`. This way the integral is computed numerically and the bvcdf function is avoided.

**Comment by Bartdoekemeijer** [comment]
Thanks for finding this issue! It indeed seems to be something with the integration scheme. I have considered completely removing the `bvcdf_wake` code for simplicity, but it appears to be a factor 3 faster, doing some quick runs. One solution lies in ensuring that dy and dz are nonzero, simply as:

`% Corrections to avoid numerical issues
if dy == 0
    dy = eps;
end
if dz == 0
    dz = eps;
end`

I will push this solution back to the master branch.
