### ISSUE TITLE
Lateral displacement bias in Porte-Agel wake deflection model

### ISSUE THREAD

**Issue by Bartdoekemeijer** [TUDelft-DataDrivenControl/FLORISSE_M#4]
The parameters
```
inputData.ad    = -4.5;     % lateral wake displacement bias parameter (a + bx)
inputData.bd    = -.01;     % lateral wake displacement bias parameter (a + bx)
```
in lines 218-219 of _floris_loadSettings.m_ are not used in the current implementation for the Porte-Agel wake deflection model. This leads to a fully symmetrical wake model, showing no particular bias for positive or negative yaw angles. Thus, the optimization may at any given time end up with e.g. +25 degrees yaw or -25 degrees yaw, making it sensitive to numerical issues in the optimization. This can be circumvented by manually changing the lower and upper bounds in the optimization in _floris.m_, but a better solution is to implement something similar to Jimenez for the blade rotation-induced lateral wake displacement in the Porte-Agel model. 

Is this an implementation issue, or just something not present in the original Porte-Agel model? Sjoerd Boersma and I are seeing some important discrepancies with LES data from PALM.

**Comment by RmStorm** [comment]
@Bartdoekemeijer If you agree with this implementation you can close the issue. Let me know what you think!

**Comment by Bartdoekemeijer** [comment]
Works great, thanks!
